'use strict';
const {calculateScore,evaluateRoute,makeWriteKey,retryDecision,validateEnvelope}=require('./policy.cjs');
function processPacket(packet){
 const violations=validateEnvelope(packet); if(violations.length)return{runId:packet?.runId||null,gate:packet?.gate||null,status:'Blocked',violations,results:[],summary:{candidatesIn:Array.isArray(packet?.candidates)?packet.candidates.length:0,escalated:0,watched:0,archived:0,blocked:Array.isArray(packet?.candidates)?packet.candidates.length:0,duplicatesSuppressed:0},incrementalCostUsd:0,externalActions:0,canonicalPortfolioWrites:0,aiCalls:0};
 const seen=new Set(),results=[];let duplicatesSuppressed=0;
 for(const candidate of packet.candidates){const score=calculateScore(candidate.ratings);if(candidate.claimedScore!==undefined&&Number(candidate.claimedScore)!==score){results.push({candidateId:candidate.candidateId,status:'Blocked',reason:'score_mismatch',deterministicScore:score});continue;}const decision=evaluateRoute(candidate,score);if(!decision.valid){results.push({candidateId:candidate.candidateId,status:'Blocked',reason:decision.reason,deterministicScore:score,requestedRoute:candidate.routerRecommendation});continue;}const route=decision.route;if(candidate.duplicateDisposition==='Duplicate')duplicatesSuppressed++;const targetStore=route==='Escalate'?'OIT Escalation Queue':'OIT Candidate Queue';const writeKey=makeWriteKey(packet.runId,candidate.candidateId,targetStore,packet.workflowVersion);if(seen.has(writeKey)){results.push({candidateId:candidate.candidateId,status:'NoOp',reason:'idempotent_replay',deterministicScore:score,route,writeKey});continue;}seen.add(writeKey);results.push({candidateId:candidate.candidateId,status:'Pass',deterministicScore:score,route,duplicateDisposition:candidate.duplicateDisposition,writeKey,nextTest:candidate.nextTest});}
 const count=(route)=>results.filter((x)=>x.status==='Pass'&&x.route===route).length;const blocked=results.filter((x)=>x.status==='Blocked').length;
 return{runId:packet.runId,gate:packet.gate,workflowId:packet.workflowId,workflowVersion:packet.workflowVersion,boundaryContract:packet.boundaryContract,status:blocked?'Warning':'Pass',violations:[],results,summary:{candidatesIn:packet.candidates.length,escalated:count('Escalate'),watched:count('Watch'),archived:count('Archive'),blocked,duplicatesSuppressed},controls:{manualOnly:true,scheduleEnabled:false,webhookEnabled:false,retryPolicyForUnknownOutcome:retryDecision('unknown')},incrementalCostUsd:0,externalActions:0,canonicalPortfolioWrites:0,aiCalls:0};
}
module.exports={processPacket};
