(()=>{
'use strict';
const Core=window.WorkControlCore;
const STORAGE_KEY='work-control-v1-state';
const seedState={adapterConnected:false,teams:[
{id:'SUB-OPS-006',run:'Run 006',name:'Subscription Operations',icon:'S',readiness:'Needs setup',live:'Controlled',authority:'Approval-gated',capability:'Discovers, verifies and monitors subscriptions, renewals, cost and usage.',current:'Gmail connection required'},
{id:'SYS-INT-007',run:'Run 007',name:'Systems Intelligence & Development',icon:'D',readiness:'Review',live:'Not live',authority:'None',capability:'Analyzes systems, architecture, reusable capabilities and development needs.',current:'No active assignment'},
{id:'MUNI-009',run:'Run 009',name:'Municipal Development Intelligence',icon:'M',readiness:'Review',live:'Not live',authority:'None',capability:'Researches municipal development signals and structured opportunity evidence.',current:'No active assignment'},
{id:'INV-010',run:'Run 010',name:'Vendor Invoice Overcharge Recovery',icon:'I',readiness:'Review',live:'Not live',authority:'None',capability:'Finds invoice discrepancies, recovery opportunities and supporting evidence.',current:'No active assignment'},
{id:'OPP-011',run:'Run 011',name:'Opportunity Intelligence',icon:'O',readiness:'Ready',live:'Controlled',authority:'Approval-gated',capability:'Maps, compares and challenges revenue opportunities before resources are committed.',current:'Portfolio intelligence'},
{id:'GROWTH-012',run:'Run 012',name:'Growth & Client Acquisition',icon:'G',readiness:'Ready',live:'Controlled',authority:'Approval-gated',capability:'Coordinates prospecting, acquisition workflows, evidence, delivery control and growth.',current:'No active assignment'},
{id:'SW-PROD-014',run:'Run 014',name:'Software Product Engineering',icon:'W',readiness:'Ready',live:'Controlled live',authority:'Approval-gated',capability:'Turns approved software briefs into tested, security-reviewed release candidates.',current:'Work Control v1'}],work:[
{id:'WC-V1-001',title:'Work Control v1',teamId:'SW-PROD-014',teamName:'Software Product Engineering',status:'completed',priority:'high',createdAt:'2026-08-22T21:36:00-05:00',progress:100,next:'Connect Factory execution adapter',stages:[{name:'Product brief',state:'done',detail:'Six owner workflows locked'},{name:'UX architecture',state:'done',detail:'Owner-first control model'},{name:'Implementation',state:'done',detail:'Local static control shell'},{name:'Deterministic tests',state:'done',detail:'Release suite passed'},{name:'Security review',state:'done',detail:'No remote execution path'},{name:'Release candidate',state:'done',detail:'v1 prototype ready'}],result:{summary:'Work Control v1 local prototype ready',detail:'Teams, staged run requests, work visibility, local approval decisions, results and history are implemented. Real execution remains disconnected by design.'}},
{id:'OQS-001',title:'Opportunity Quick Score',teamId:'SW-PROD-014',teamName:'Software Product Engineering',status:'completed',priority:'normal',createdAt:'2026-08-22T19:47:00-05:00',progress:100,next:'Complete',stages:[{name:'Product brief',state:'done',detail:'PASS'},{name:'Specification',state:'done',detail:'PASS'},{name:'Architecture',state:'done',detail:'PASS'},{name:'Implementation',state:'done',detail:'PASS'},{name:'Testing',state:'done',detail:'18/18 PASS'},{name:'Security',state:'done',detail:'PASS'}],result:{summary:'Release package completed',detail:'18/18 deterministic tests passed; security review passed; $0 spend; no external deployment.'}},
{id:'SUB-006-CONNECT',title:'Subscription monitoring connection',teamId:'SUB-OPS-006',teamName:'Subscription Operations',status:'blocked',priority:'normal',createdAt:'2026-08-21T10:15:00-05:00',progress:45,next:'Connect intended Gmail account',stages:[{name:'Workflow baseline',state:'done',detail:'Available'},{name:'Credential selection',state:'blocked',detail:'Owner account connection required'},{name:'Live monitoring',state:'queued',detail:'Not started'}],result:{summary:'Blocked on owner configuration',detail:'No live monitoring is claimed until the intended Gmail credential is connected and verified.'}}],approvals:[
{id:'APP-WC-PREVIEW',title:'Deploy Work Control preview',team:'Software Product Engineering',workId:'WC-V1-001',status:'pending',target:'Vercel Preview',environment:'Non-production',actions:1,spend:'$0',production:'No',reason:'Make the owner console accessible from another device. Local approval in v1 will not trigger deployment.'}],history:[
{id:'H-WC-READY',at:'2026-08-22T21:36:00-05:00',title:'Work Control v1 release candidate prepared',detail:'Owner control shell completed with execution adapter intentionally disconnected.',type:'release'},
{id:'H-V01',at:'2026-08-22T21:22:00-05:00',title:'Factory v0.1.0 baseline frozen',detail:'Recovery and release branches anchored to known-good commit 37392d74728a44c3e502959c09e6400de40b846e.',type:'governance'},
{id:'H-OQS',at:'2026-08-22T19:47:00-05:00',title:'Opportunity Quick Score completed',detail:'Run 014 completed the full controlled software loop; 18/18 tests passed.',type:'result'},
{id:'H-R14',at:'2026-08-22T18:35:00-05:00',title:'Software Product Engineering entered controlled live',detail:'Run 014 G6 passed with approval-gated external authority.',type:'governance'}]};
let state=loadState(),workFilter='all';
function clone(v){return JSON.parse(JSON.stringify(v));}
function loadState(){try{const saved=localStorage.getItem(STORAGE_KEY);if(!saved)return clone(seedState);const parsed=JSON.parse(saved);return{...clone(seedState),...parsed,teams:clone(seedState.teams),adapterConnected:false};}catch{return clone(seedState);}}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify({...state,adapterConnected:false}));}
function esc(v){return String(v??'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));}
function formatTime(iso){try{return new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(iso));}catch{return iso;}}
function teamById(id){return state.teams.find(t=>t.id===id);}function statusLabel(s){return s.charAt(0).toUpperCase()+s.slice(1);}function statusClass(s){return['running','completed','blocked','queued'].includes(s)?`status-pill--${s}`:'';}
function badge(v){const c=v==='Ready'?'badge--green':v==='Needs setup'?'badge--amber':'';return`<span class="badge ${c}">${esc(v)}</span>`;}
function navigate(view){document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('is-active',b.dataset.view===view));document.querySelectorAll('[data-view-panel]').forEach(p=>p.classList.toggle('is-active',p.dataset.viewPanel===view));const labels={overview:['Owner workspace','Overview'],teams:['Digital workforce','Teams'],work:['Assignments','Work'],approvals:['Owner attention','Approvals'],history:['Audit trail','History']};document.getElementById('view-eyebrow').textContent=labels[view][0];document.getElementById('view-title').textContent=labels[view][1];render();}
function render(){renderMetrics();renderOwnerAttention();renderOverviewWork();renderTeams();renderWork();renderApprovals();renderHistory();}
function renderMetrics(){const s=Core.summarize(state);const m=[['Ready teams',s.readyTeams,'available for controlled work'],['Running',s.running,'assignments in execution'],['Need you',s.pendingApprovals+s.blocked,'approvals + blockers'],['Completed',s.completed,'visible results']];document.getElementById('metric-grid').innerHTML=m.map(([l,v,n])=>`<article class="metric-card"><span>${esc(l)}</span><strong>${v}</strong><small>${esc(n)}</small></article>`).join('');}
function renderOwnerAttention(){const pending=state.approvals.filter(a=>a.status==='pending').map(a=>({title:a.title,detail:`${a.environment} · ${a.spend} spend ceiling`,badge:'Approval',view:'approvals'}));const blocked=state.work.filter(w=>w.status==='blocked').map(w=>({title:w.title,detail:w.next,badge:'Blocked',view:'work'}));const items=[...pending,...blocked];document.getElementById('owner-attention').innerHTML=items.length?items.map(i=>`<button class="attention-item" data-navigate="${i.view}"><span><strong>${esc(i.title)}</strong><span>${esc(i.detail)}</span></span><span class="badge ${i.badge==='Approval'?'badge--amber':'badge--red'}">${esc(i.badge)}</span></button>`).join(''):`<div class="empty-state"><strong>Nothing needs you</strong>No owner intervention is currently recorded.</div>`;}
function workMarkup(w){const t=teamById(w.teamId),p=Number.isFinite(w.progress)?w.progress:Core.percentFromStages(w.stages);return`<article class="work-item" data-work-id="${esc(w.id)}" tabindex="0" role="button"><div class="work-title"><strong>${esc(w.title)}</strong><span>${esc(w.id)} · ${esc(w.priority||'normal')} priority</span></div><div class="work-team">${esc(t?.name||w.teamName||'Unknown team')}</div><div><span class="status-pill ${statusClass(w.status)}">${esc(statusLabel(w.status))}</span></div><div class="work-progress-wrap"><div class="work-next">${esc(w.next||'—')}</div><div class="work-progress"><i style="width:${Math.max(0,Math.min(100,p))}%"></i></div></div><button class="quiet-button" type="button" data-work-open="${esc(w.id)}">Open</button></article>`;}
function renderOverviewWork(){const visible=state.work.filter(w=>w.status!=='completed').slice(0,3);document.getElementById('overview-work').innerHTML=(visible.length?visible:state.work.slice(0,2)).map(workMarkup).join('');}
function teamMarkup(t){return`<article class="team-card"><div class="team-head"><div class="team-icon">${esc(t.icon)}</div>${badge(t.readiness)}</div><h3>${esc(t.name)}</h3><div class="run-id">${esc(t.run)} · ${esc(t.id)}</div><p>${esc(t.capability)}</p><div class="team-meta"><span>${esc(t.live)}</span><span>${esc(t.authority)}</span></div><div class="team-actions"><button class="secondary-button" data-team-detail="${esc(t.id)}">Details</button><button class="primary-button" data-run-team="${esc(t.id)}">Run team</button></div></article>`;}
function renderTeams(){document.getElementById('overview-teams').innerHTML=state.teams.filter(t=>t.readiness==='Ready').slice(0,4).map(teamMarkup).join('');const q=(document.getElementById('team-search')?.value||'').toLowerCase().trim();const filtered=state.teams.filter(t=>!q||`${t.name} ${t.capability} ${t.run}`.toLowerCase().includes(q));document.getElementById('teams-grid').innerHTML=filtered.map(teamMarkup).join('')||`<div class="empty-state"><strong>No teams found</strong>Try another search.</div>`;}
function renderWork(){const f=state.work.filter(w=>workFilter==='all'||w.status===workFilter);document.getElementById('work-list').innerHTML=f.map(workMarkup).join('')||`<div class="empty-state"><strong>No work in this state</strong>Choose another filter or stage a new team request.</div>`;}
function renderApprovals(){document.getElementById('approvals-list').innerHTML=[...state.approvals].sort((a,b)=>(a.status==='pending'?-1:1)-(b.status==='pending'?-1:1)).map(a=>`<article class="approval-card"><div class="team-head"><span class="badge ${a.status==='pending'?'badge--amber':a.status==='approved'?'badge--green':'badge--red'}">${esc(a.status)}</span><span class="run-id">${esc(a.id)}</span></div><h3>${esc(a.title)}</h3><p>${esc(a.reason)}</p><div class="approval-facts"><div class="approval-fact"><span>Target</span><strong>${esc(a.target)}</strong></div><div class="approval-fact"><span>Environment</span><strong>${esc(a.environment)}</strong></div><div class="approval-fact"><span>External actions</span><strong>${esc(a.actions)}</strong></div><div class="approval-fact"><span>Spend ceiling</span><strong>${esc(a.spend)}</strong></div><div class="approval-fact"><span>Production</span><strong>${esc(a.production)}</strong></div><div class="approval-fact"><span>Transmission</span><strong>Disconnected</strong></div></div>${a.status==='pending'?`<div class="approval-actions"><button class="danger-button" data-approval="${esc(a.id)}" data-decision="rejected">Reject</button><button class="primary-button" data-approval="${esc(a.id)}" data-decision="approved">Approve locally</button></div>`:`<div class="approval-decision">Decision recorded locally: <strong>${esc(a.status)}</strong>. No authority was transmitted.</div>`}</article>`).join('');}
function renderHistory(){const q=(document.getElementById('history-search')?.value||'').toLowerCase().trim();const items=[...state.history].sort((a,b)=>new Date(b.at)-new Date(a.at)).filter(h=>!q||`${h.title} ${h.detail} ${h.type}`.toLowerCase().includes(q));document.getElementById('history-list').innerHTML=items.map(h=>`<article class="history-item"><time class="history-time">${esc(formatTime(h.at))}</time><div class="history-marker"></div><div class="history-copy"><strong>${esc(h.title)}</strong><p>${esc(h.detail)}</p></div></article>`).join('')||`<div class="empty-state"><strong>No history found</strong>Try another search.</div>`;}
function openDrawer(html){document.getElementById('drawer-content').innerHTML=html;document.getElementById('drawer-backdrop').hidden=false;const d=document.getElementById('drawer');d.classList.add('is-open');d.setAttribute('aria-hidden','false');setTimeout(()=>d.querySelector('textarea,button,select')?.focus(),0);}
function closeDrawer(){const d=document.getElementById('drawer');d.classList.remove('is-open');d.setAttribute('aria-hidden','true');document.getElementById('drawer-backdrop').hidden=true;}
function openRunDrawer(teamId){const t=teamById(teamId)||state.teams[0];openDrawer(`<p class="eyebrow">Run team</p><h2>${esc(t.name)}</h2><p class="drawer-subtitle">Describe the outcome. Work Control will stage a governed request; v1 will not claim dispatch while the execution adapter is disconnected.</p><div class="notice notice--amber"><strong>Execution adapter disconnected.</strong> Submitting creates a local work request only.</div><form id="run-team-form" class="form-grid" data-team-id="${esc(t.id)}"><label>Assignment<textarea name="instruction" required minlength="3" placeholder="Example: Audit the current Amazon sourcing software and return a prioritized improvement plan."></textarea></label><label>Priority<select name="priority"><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option><option value="low">Low</option></select></label><div class="drawer-section"><h3>Authority posture</h3><div class="posture-list"><div><span>External authority</span><strong>${esc(t.authority)}</strong></div><div><span>UI dispatch</span><strong>Disabled</strong></div><div><span>Spend</span><strong>$0 authorized</strong></div></div></div><div class="drawer-actions"><button type="button" class="quiet-button" data-close-drawer>Cancel</button><button type="submit" class="primary-button">Stage request</button></div></form>`);}
function openTeamDetail(id){const t=teamById(id);if(!t)return;const works=state.work.filter(w=>w.teamId===id);openDrawer(`<p class="eyebrow">${esc(t.run)}</p><h2>${esc(t.name)}</h2><p class="drawer-subtitle">${esc(t.capability)}</p><div class="drawer-section"><h3>Current posture</h3><div class="posture-list"><div><span>Readiness</span><strong>${esc(t.readiness)}</strong></div><div><span>Live state</span><strong>${esc(t.live)}</strong></div><div><span>External authority</span><strong>${esc(t.authority)}</strong></div><div><span>Current work</span><strong>${esc(t.current)}</strong></div></div></div><div class="drawer-section"><h3>Visible work</h3>${works.length?works.map(w=>`<button class="attention-item" data-work-open="${esc(w.id)}"><span><strong>${esc(w.title)}</strong><span>${esc(statusLabel(w.status))}</span></span></button>`).join(''):`<div class="empty-state">No visible assignments.</div>`}</div><div class="drawer-actions"><button class="primary-button" data-run-team="${esc(t.id)}">Run team</button></div>`);}
function openWorkDetail(id){const w=state.work.find(x=>x.id===id);if(!w)return;openDrawer(`<p class="eyebrow">${esc(w.id)}</p><h2>${esc(w.title)}</h2><p class="drawer-subtitle">${esc(w.teamName)} · ${esc(statusLabel(w.status))} · ${esc(w.priority||'normal')} priority</p><div class="drawer-section"><h3>Workflow</h3><div class="stage-list">${(w.stages||[]).map(s=>`<div class="stage stage--${esc(s.state)}"><i>${s.state==='done'?'✓':s.state==='active'?'•':s.state==='blocked'?'!':'○'}</i><strong>${esc(s.name)}</strong><span>${esc(s.detail||s.state)}</span></div>`).join('')}</div></div><div class="drawer-section"><h3>Next</h3><div class="result-box"><strong>${esc(w.next||'No next action')}</strong>${w.status==='queued'?'Execution will remain blocked until a real Factory adapter is connected.':'This is the latest recorded next action.'}</div></div><div class="drawer-section"><h3>Result</h3><div class="result-box"><strong>${esc(w.result?.summary||'No result yet')}</strong>${esc(w.result?.detail||'')}</div></div><div class="drawer-section"><h3>Control evidence</h3><div class="code-line">source=${esc(w.source||'seeded-control-snapshot')} · external_dispatch=${state.adapterConnected?'connected':'disconnected'}</div></div>`);}
function stageRun(form){const t=teamById(form.dataset.teamId),fd=new FormData(form);try{const r=Core.createRunRequest({teamId:t.id,teamName:t.name,instruction:fd.get('instruction'),priority:fd.get('priority'),now:new Date().toISOString()});const g=Core.dispatchGuard(state.adapterConnected);r.next=g.allowed?'Dispatch through Factory adapter':'Connect execution adapter';state.work.unshift(r);state.history.unshift({id:`H-${r.id}`,at:r.createdAt,title:'Team request staged',detail:`${t.name}: ${r.title}. Factory dispatch not claimed.`,type:'request'});saveState();closeDrawer();navigate('work');}catch(err){alert(err.message==='INSTRUCTION_REQUIRED'?'Enter a clear assignment.':'The request could not be staged.');}}
function decideApproval(id,decision){const i=state.approvals.findIndex(a=>a.id===id);if(i<0)return;try{const r=Core.applyApproval(state.approvals[i],decision,new Date().toISOString());state.approvals[i]=r.approval;state.history.unshift(r.event);saveState();render();}catch{alert('This approval has already been decided.');}}
document.addEventListener('click',e=>{const nav=e.target.closest('[data-view]');if(nav){navigate(nav.dataset.view);return;}const jump=e.target.closest('[data-navigate]');if(jump){navigate(jump.dataset.navigate);return;}const run=e.target.closest('[data-run-team]');if(run){openRunDrawer(run.dataset.runTeam);return;}const td=e.target.closest('[data-team-detail]');if(td){openTeamDetail(td.dataset.teamDetail);return;}const w=e.target.closest('[data-work-open],[data-work-id]');if(w){openWorkDetail(w.dataset.workOpen||w.dataset.workId);return;}const a=e.target.closest('[data-approval]');if(a){decideApproval(a.dataset.approval,a.dataset.decision);return;}if(e.target.closest('[data-close-drawer]')){closeDrawer();return;}const f=e.target.closest('[data-filter]');if(f){workFilter=f.dataset.filter;document.querySelectorAll('#work-filter button').forEach(b=>b.classList.toggle('is-active',b===f));renderWork();}});
document.addEventListener('submit',e=>{if(e.target.id==='run-team-form'){e.preventDefault();stageRun(e.target);}});
document.getElementById('global-run-team').addEventListener('click',()=>openRunDrawer(state.teams.find(t=>t.readiness==='Ready')?.id||state.teams[0].id));document.getElementById('drawer-close').addEventListener('click',closeDrawer);document.getElementById('drawer-backdrop').addEventListener('click',closeDrawer);document.getElementById('team-search').addEventListener('input',renderTeams);document.getElementById('history-search').addEventListener('input',renderHistory);document.getElementById('reset-demo').addEventListener('click',()=>{if(confirm('Reset local Work Control demo data?')){localStorage.removeItem(STORAGE_KEY);state=clone(seedState);navigate('overview');}});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDrawer();if(e.target.matches('input,textarea,select'))return;const map={'1':'overview','2':'teams','3':'work','4':'approvals','5':'history'};if(map[e.key])navigate(map[e.key]);});render();
})();
