from pathlib import Path

p = Path('/opt/sentinelx-cloud-core/agent-factory/work-control-worker-tools-20260825-v1/run015-executor.cjs')
s = p.read_text()

s = s.replace("EXECUTOR_VERSION='2026-08-28.4'", "EXECUTOR_VERSION='2026-08-28.5'")
s = s.replace(
    "const CRITICAL=['visualHierarchy','uxClarity','responsiveExecution','accessibility'];\nconst WEIGHTS=",
    "const CRITICAL=['visualHierarchy','uxClarity','responsiveExecution','accessibility'];\n"
    "const VISUAL_KEYS=['visualHierarchy','typography','layoutSpacing','componentQuality','uxClarity','interactionPolish','brandDistinction'];\n"
    "const RESP_KEYS=['responsiveExecution','accessibility','statesAndFeedback'];\n"
    "const WEIGHTS="
)
s = s.replace(
    "const BENCH=obj({targetSummary:{type:'string'},verifiedFacts:arr,preserveStrings:arr,currentIssues:arr,benchmarkPrinciples:arr,audience:arr,sourceNotes:arr});",
    "const BENCH=obj({targetSummary:{type:'string'},verifiedFacts:arr,preserveStrings:arr,currentIssues:arr,benchmarkPrinciples:arr,benchmarkBoard:arr,audience:arr,sourceNotes:arr});"
)
s = s.replace(
    "const QA=obj({verdict:{type:'string',enum:['PASS','REVISE','REJECT']},functionalityPreserved:{type:'boolean'},evidenceComplete:{type:'boolean'},blockers:arr,rationale:arr});",
    "const QA=obj({verdict:{type:'string',enum:['PASS','REVISE','REJECT']},functionalityPreserved:{type:'boolean'},evidenceComplete:{type:'boolean'},blockers:arr,rationale:arr});\n"
    "const CHALLENGER=obj({verdict:{type:'string',enum:['PASS','REVISE']},agencyQuality:{type:'boolean'},topDefects:arr,repairDirectives:arr,preserveStrengths:arr,benchmarkGap:arr});"
)

needle = "function urlOf(i){const m=String(i||'').match(/https:\\/\\/[^\\s)\\]}>]+/i);if(!m)throw Error('UIX_TARGET_URL_REQUIRED');return new URL(m[0]).href;}function weighted(s){let n=0;for(const[k,w]of Object.entries(WEIGHTS))n+=Number(s[k]||0)*w/100;return Math.round(n*10)/10;}"
if needle not in s:
    raise SystemExit('weighted marker missing')
s = s.replace(
    needle,
    needle + "function gateScore(scores,keys){let n=0,d=0;for(const k of keys){const w=Number(WEIGHTS[k]||1);n+=Number(scores[k]||0)*w;d+=w;}return Math.round((d?n/d:0)*10)/10;}"
)

old_prompt = "'Use at most ONE read-only web search call. Inspect the target and relevant best-in-class service-site principles. Do not copy competitors. The governed executor itself handles workspace, screenshots, rendering and later QA; do not report those executor capabilities as unavailable. Extract factual public content. preserveStrings MUST contain only short literal user-facing strings actually observed on the target or supplied in the authoritative prior handoff (brand names, navigation labels, service names, contact labels); never put requirements, instructions, summaries, sentences, inferred content, or prose about what must be preserved in preserveStrings. Identify weaknesses. Do not invent claims.'"
new_prompt = "'Use at most ONE read-only web search call. Inspect the target and select 3–5 strong contemporary benchmark sites or references appropriate to this exact industry and audience. Do not copy them. Put each reference in benchmarkBoard as: Name — URL — specific principles worth matching (typography, composition, hierarchy, imagery, section rhythm, navigation, mobile execution, signature detail). The governed executor itself handles workspace, screenshots, rendering and later QA; do not report those executor capabilities as unavailable. Extract factual public content. preserveStrings MUST contain only short literal user-facing strings actually observed on the target or supplied in the authoritative prior handoff (brand names, navigation labels, service names, contact labels); never put requirements, instructions, summaries, sentences, inferred content, or prose about what must be preserved in preserveStrings. Identify weaknesses. Do not invent claims.'"
if old_prompt not in s:
    raise SystemExit('benchmark prompt marker missing')
s = s.replace(old_prompt, new_prompt)

start = s.index(" async function repairPreservation()")
end = s.index("\n await repairPreservation();", start)
new_preserve = """ async function repairPreservation(scope='initial'){for(let n=1;n<=2;n++){const st=checks(html,benchmark.preserveStrings),fail=st.filter(x=>x.status!=='PASS'),base=scope==='initial'?dir:path.join(dir,'iterations');const fn=scope==='initial'?(n===1?'07-static-checks.json':`p${n-1}-static-checks.json`):`${scope}-p${n-1}-static-checks.json`;write(path.join(base,fn),st);if(!fail.length){progress('Functional Preservation Gate','PASS',`scope=${scope}; attempt=${n}; checks=${st.length}`);return;}const c=cost(),limit=Number(command.modelBudgetCents||10);if(c>=Math.max(0,limit-2.5)){progress('Functional Preservation Gate','BLOCKED_BUDGET',`scope=${scope}; estimated=${c}c; failures=${fail.map(x=>x.id).join(',')}`);throw Error(`UIX_FUNCTIONAL_PRESERVATION_BUDGET_${fail.slice(0,4).map(x=>x.id).join('_')}`);}progress('Functional Preservation Gate','REVISE',`scope=${scope}; attempt=${n}; failures=${fail.map(x=>x.id).join(',')}`);const im=await text(`Frontend Polish Engineer — Preservation Repair ${scope}.${n}`,['ROLE: Frontend Polish Engineer. Repair ONLY the governed runtime artifact; do not redesign from scratch.',`Current HTML:${html}`,`Failed deterministic preservation checks:${JSON.stringify(fail)}`,`Authoritative literal preservation strings:${JSON.stringify(literalPreserveStrings(benchmark.preserveStrings))}`,'Make the smallest coherent production-quality change that restores every missing legitimate literal label/journey without removing accessibility, responsive behavior, design quality or verified content. Exact preserved labels may appear in navigation, section copy or CTAs where semantically appropriate. Do not add unsupported claims, external scripts, network code, tracking or live form submission. Return one complete self-contained index.html and implementation notes.'].join('\\n'),IMPL,`uix_preservation_repair_${scope}_${n}`,12000,0,'medium');html=im.html;const pp=path.join(dir,`index.${scope}.p${n}.html`);fs.writeFileSync(pp,html);fs.writeFileSync(htmlPath,html);stages[stages.length-1].artifactPath=htmlPath;write(path.join(dir,`iterations/${scope}-p${n}-implementation.json`),{notes:im.implementationNotes,artifact:{path:htmlPath,sha256:sha(htmlPath),bytes:fs.statSync(htmlPath).size},preservationRepair:true,scope});}const st=checks(html,benchmark.preserveStrings),fail=st.filter(x=>x.status!=='PASS');write(path.join(dir,`iterations/${scope}-p2-static-checks.json`),st);if(fail.length)throw Error(`UIX_FUNCTIONAL_PRESERVATION_FAIL_${fail.slice(0,4).map(x=>x.id).join('_')}`);}"""
s = s[:start] + new_preserve + s[end:]
s = s.replace(" await repairPreservation();", " await repairPreservation('initial');", 1)

start = s.index(" async function review(v){")
end = s.index("\n finalReview=await review(0);", start)
new_review = """ async function review(v){const tag=v===0?'':`-r${v}`,base=v===0?dir:path.join(dir,'iterations');let st=checks(html,benchmark.preserveStrings);write(path.join(base,v===0?'07-static-checks.json':`r${v}-static-checks.json`),st);const fail=st.filter(x=>x.status!=='PASS');if(fail.length)throw Error(`UIX_FUNCTIONAL_PRESERVATION_FAIL_${fail.slice(0,4).map(x=>x.id).join('_')}`);const aft=(await renderer('/render',{commandId:id,target:`file:///artifacts/${id}/index.html`,prefix:`after${tag}`})).results;write(path.join(base,v===0?'after-evidence.json':`r${v}-after-evidence.json`),aft);const audit=await renderer('/audit',{commandId:id,target:`file:///artifacts/${id}/index.html`});write(path.join(base,v===0?'interaction-audit.json':`r${v}-interaction-audit.json`),audit);const ap=['mobile','tablet','desktop'].map(x=>aft[x].path);
  const{ x:access }=await vision(v===0?'Responsive & Accessibility Specialist':`Responsive & Accessibility Specialist — Revision ${v}`,['ROLE: Responsive & Accessibility Specialist. AFTER images are mobile, tablet, desktop.',`Browser interaction audit:${JSON.stringify(audit)}`,`Static checks:${JSON.stringify(st)}`,`Interaction spec:${JSON.stringify(ix)}`,'Evaluate responsive composition and accessibility using the browser audit as runtime evidence. Do not require forms or form validation when the approved artifact deliberately has no submitting forms.'].join('\\n'),ACCESS,`uix_accessibility_r${v}`,4000,ap);
  const{ x:score }=await vision(v===0?'Visual Acceptance Scorer':`Visual Acceptance Scorer — Revision ${v}`,['ROLE: Visual Acceptance Scorer. Images are BEFORE mobile/tablet/desktop followed by AFTER mobile/tablet/desktop.',`Art:${JSON.stringify(art)}`,`UX:${JSON.stringify(ux)}`,`Benchmark board:${JSON.stringify(benchmark.benchmarkBoard)}`,`Runtime audit:${JSON.stringify(audit)}`,'Score AFTER conservatively against high-end bespoke contemporary service/product sites, not merely the weak original. UIX 92 means genuinely production-grade; 96+ rare. Be scope-aware: statesAndFeedback covers applicable navigation, CTA, menu/disclosure and contact-link feedback; do not demand transactional/form states absent from approved scope. Runtime audit may prove interactions not visible in screenshots. Do not reward generic AI aesthetics.'].join('\\n'),SCORE,`uix_score_r${v}`,5000,[...bp,...ap],'medium');score.weighted=weighted(score.scores);const visualGate=gateScore(score.scores,VISUAL_KEYS),responsiveAccessibilityGate=Math.min(...RESP_KEYS.map(k=>Number(score.scores[k]||0)));write(path.join(base,v===0?'09-uix-score.json':`r${v}-uix-score.json`),{...score,visualGate,responsiveAccessibilityGate});
  const{ x:challenger }=await vision(v===0?'Visual Design Challenger':`Visual Design Challenger — Revision ${v}`,['ROLE: Visual Design Challenger. You are a demanding creative director, not the final compliance auditor. Images are BEFORE mobile/tablet/desktop then AFTER mobile/tablet/desktop.',`Benchmark board:${JSON.stringify(benchmark.benchmarkBoard)}`,`Benchmark principles:${JSON.stringify(benchmark.benchmarkPrinciples)}`,`Art direction:${JSON.stringify(art)}`,`UX:${JSON.stringify(ux)}`,`Current score:${JSON.stringify(score)}`,'Judge the AFTER artifact against the benchmark board and the standard of a strong contemporary design agency / top-tier AI website builder. Do not pass merely because it is cleaner than the original. Identify at most FIVE highest-impact visual/taste defects. Make each repair directive concrete and surgical. Preserve what is already strong. agencyQuality=true only if this could plausibly be mistaken for polished bespoke agency work rather than a generic AI template.'].join('\\n'),CHALLENGER,`uix_challenger_r${v}`,4500,[...bp,...ap],'medium');write(path.join(base,v===0?'10-design-challenger.json':`r${v}-design-challenger.json`),challenger);
  const{ x:qa,r:qar }=await vision(v===0?'Independent Visual Quality Auditor':`Independent Visual Quality Auditor — Revision ${v}`,['ROLE: Independent Visual Quality Auditor. You did not implement this artifact. Images are BEFORE mobile/tablet/desktop then AFTER mobile/tablet/desktop.',`UIX score:${JSON.stringify(score)}`,`Visual gate:${visualGate}`,`Responsive/accessibility gate:${responsiveAccessibilityGate}`,`Design Challenger:${JSON.stringify(challenger)}`,`Accessibility:${JSON.stringify(access)}`,`Browser interaction/content audit:${JSON.stringify(audit)}`,`Static preservation:${JSON.stringify(st)}`,'Challenge the evidence. PASS only if functionality is preserved, evidence is complete, overall UIX >=92, visual/taste gate >=92, responsive/accessibility gate >=90, all critical dimensions >=90, the Design Challenger says agencyQuality=true/PASS, and no critical blockers remain. Use browser audit and headings/links inventory as evidence for interactions/below-fold content. Do not require non-applicable form submission/validation states. Do not waive real failures.'].join('\\n'),QA,`uix_qa_r${v}`,4000,[...bp,...ap]);write(path.join(base,v===0?'11-independent-qa.json':`r${v}-independent-qa.json`),qa);const cf=CRITICAL.filter(k=>Number(score.scores[k])<90),functionalPass=st.every(x=>x.status==='PASS')&&qa.functionalityPreserved,pass=functionalPass&&score.weighted>=92&&visualGate>=92&&responsiveAccessibilityGate>=90&&!cf.length&&!score.criticalBlockers.length&&access.status==='PASS'&&audit.status==='PASS'&&challenger.verdict==='PASS'&&challenger.agencyQuality&&qa.verdict==='PASS'&&qa.evidenceComplete&&!qa.blockers.length;return{version:v,staticChecks:st,after:aft,audit,access,score,challenger,qa,visualGate,responsiveAccessibilityGate,functionalGate:functionalPass?100:0,criticalFailures:cf,pass,qaResponse:qar};}"""
s = s[:start] + new_review + s[end:]

start = s.index(" for(let r=1;r<=2&&!finalReview.pass;r++)")
end = s.index("\n const a=agg", start)
new_loop = """ for(let r=1;r<=5&&!finalReview.pass;r++){const c=cost(),limit=Number(command.modelBudgetCents||10);if(c>=Math.max(0,limit-2.5)){progress('Iteration Controller','BLOCKED_BUDGET',`estimated=${c}c; limit=${limit}c`);break;}progress('Iteration Controller','REVISE',`revision=${r}; score=${finalReview.score.weighted}; visual=${finalReview.visualGate}; responsiveA11y=${finalReview.responsiveAccessibilityGate}; cost=${c}c`);version=r;const repair=[`REVISION ${r}. Perform a TARGETED repair of the existing runtime-generated artifact. Do not broadly regenerate the site.`,`Current HTML:${html}`,`Visual Design Challenger — top defects:${JSON.stringify((finalReview.challenger.topDefects||[]).slice(0,5))}`,`Visual Design Challenger — repair directives:${JSON.stringify((finalReview.challenger.repairDirectives||[]).slice(0,5))}`,`Preserve strengths:${JSON.stringify(finalReview.challenger.preserveStrengths||[])}`,`Hard accessibility repairs:${JSON.stringify(finalReview.access.requiredRepairs||[])}`,`Browser audit failures:${JSON.stringify((finalReview.audit.checks||[]).filter(x=>x.status!=='PASS'))}`,`Independent QA blockers:${JSON.stringify(finalReview.qa.blockers||[])}`,'Fix the Challenger’s highest-impact defects first. Preserve verified content, working journeys, and strengths. Make meaningful composition, typography, hierarchy, imagery/motif, spacing, component and interaction improvements only where the critique points. Do not merely recolor or rewrite everything. Keep the artifact self-contained and production-polished.'];await implement(`Frontend Polish Engineer — Revision ${r}`,repair.join('\\n'));await repairPreservation(`r${r}`);finalReview=await review(r);finalQaResponse=finalReview.qaResponse;}"""
s = s[:start] + new_loop + s[end:]

old = "receipt.uix={score:finalReview.score.weighted,scores:finalReview.score.scores,criticalFailures:finalReview.criticalFailures,browserAuditStatus:finalReview.audit.status,accessibilityStatus:finalReview.access.status,qaVerdict:finalReview.qa.verdict,revision:finalReview.version};"
new = "receipt.uix={score:finalReview.score.weighted,scores:finalReview.score.scores,visualGate:finalReview.visualGate,responsiveAccessibilityGate:finalReview.responsiveAccessibilityGate,functionalGate:finalReview.functionalGate,criticalFailures:finalReview.criticalFailures,browserAuditStatus:finalReview.audit.status,accessibilityStatus:finalReview.access.status,challengerVerdict:finalReview.challenger.verdict,agencyQuality:finalReview.challenger.agencyQuality,qaVerdict:finalReview.qa.verdict,revision:finalReview.version};"
if old not in s:
    raise SystemExit('receipt marker missing')
s = s.replace(old, new)
s = s.replace(
    "weighted UIX=${finalReview.score.weighted}; criticalFailures=",
    "weighted UIX=${finalReview.score.weighted}; visualGate=${finalReview.visualGate}; responsiveAccessibilityGate=${finalReview.responsiveAccessibilityGate}; challenger=${finalReview.challenger.verdict}/${finalReview.challenger.agencyQuality?'AGENCY':'NOT_AGENCY'}; criticalFailures="
)

p.write_text(s)
print('Run 015 executor upgraded to 2026-08-28.5')
