const eBayMotors = {
    "Vehicles": {
      "Cars & Trucks": [],
      "Classic Cars": [],
      "Collector Cars": [],
      "Commercial Trucks": [],
      "Electric & Hybrid Cars": [],
      "Exotic Cars": [],
      "Boats": [],
      "Motorcycles": [],
      "Powersports": [],
      "RVs & Campers": [],
      "Trailers": [],
      "Other Vehicles": [],
    },
    "Car & Truck Parts": {
      "Air & Fuel Delivery": [],
      "Air Conditioning & Heating": [],
      "Brakes & Brake Parts": [],
      "Engine Cooling": [],
      "Engines & Engine Parts": [],
      "Exhaust & Emission Systems": [],
      "Exterior Parts & Accessories": [],
      "Ignition Systems & Components": [],
      "Interior Parts & Accessories": [],
      "Lighting & Lamps": [],
      "Starters, Alternators, ECUs & Wiring": [],
      "Steering & Suspension": [],
      "Towing Parts & Accessories": [],
      "Transmission & Drivetrain": [],
    },
    "Wheels & Tires": {
      "Tires": [],
      "Tire Pressure Monitoring Sensors": [],
      "Wheels": [],
      "Wheel Hub Caps, Center Caps & Trim Rings": [],
      "Wheel Nuts, Bolts & Studs": [],
      "Wheel Spacers, Adapters & Hub Centric Rings": [],
      "Wheel & Tire Accessories": [],
      "Wheel & Tire Packages": [],
      "Valve Stems & Caps": [],
    },
    "Motorcycle Parts": {
      "Air Intake & Fuel Delivery": [],
      "Body & Frame": [],
      "Brakes & Brake Parts": [],
      "Electrical & Ignition Components": [],
      "Engines & Engine Parts": [],
      "Exhaust & Emission Systems": [],
      "Foot Controls, Pedals & Pegs": [],
      "Handlebars, Grips & Controls": [],
      "Instruments & Gauges": [],
      "Lighting & Lamps": [],
      "Suspension & Handling": [],
      "Transmission & Drivetrain": [],
      "Wheels, Tires & Parts": [],
    },
    "ATV, UTV, and Side-by-Side Parts": {
      "Air Intake & Fuel Delivery": [],
      "Body & Frame": [],
      "Brakes & Brake Parts": [],
      "Electrical & Ignition Components": [],
      "Engines & Engine Parts": [],
      "Exhaust & Emission Systems": [],
      "Footrests, Pedals & Pegs": [],
      "Lighting & Lamps": [],
      "Seats, Parts & Accessories": [],
      "Steering & Suspension": [],
      "Towing, Recovery & Accessories": [],
      "Transmission & Drivetrain": [],
      "Wheels, Tires & Parts": [],
    },
    "Boat Parts": {
      "Accessories & Gear": [],
      "Anchoring & Docking": [],
      "Controls & Steering": [],
      "Electrical & Lighting": [],
      "Electronics & Navigation": [],
      "Inboard Engines & Components": [],
      "Outboard Engines & Components": [],
      "Plumbing & Ventilation": [],
      "Propellers": [],
      "Sterndrive Motors & Components": [],
    },
    "Other Vehicle Parts": {
      "Apparel, Protective Gear & Merchandise": [],
      "Aviation Parts": [],
      "Commercial Truck Parts": [],
      "Golf Cart Parts": [],
      "In-Car Technology, GPS & Security": [],
      "Motorcycle Maintenance, Stands & Towing": [],
      "Performance & Racing Parts": [],
      "Personal Watercraft Parts": [],
      "RV, Trailer & Camper Parts": [],
      "Snowmobile Parts": [],
    },
    "Automotive Tools & Supplies": {
      "Air Compressors": [],
      "Air Tools": [],
      "Auto Safety Kits & Supplies": [],
      "Auto Tools Boxes & Storage": [],
      "Automotive Cleaning & Detailing": [],
      "Automotive Oils & Fluids": [],
      "Automotive Paints & Supplies": [],
      "Automotive Specialty Tools": [],
      "Battery Testers & Chargers": [],
      "Diagnostic Service Tools": [],
      "Hand Tools": [],
      "Power Tools": [],
      "Shop & Garage Equipment & Supplies": [],
    },
    "Safety & Security Accessories": {
      "Safety": [],
      "Security": [],
    },
    "Automotive Accessories": {
      "Emblems & Ornaments": [],
      "Floor Mats & Carpets": [],
      "Hub Caps & Center Caps": [],
      "Motorcycle Fairings & Body Kits": [],
      "Motorcycle Helmets": [],
      "Remote Entry System Kits": [],
      "Running Boards & Step Bars": [],
      "Seat Covers": [],
      "Trailer Hitches": [],
      "Truck Bed Accessories": [],
    },
  };
  
  export default eBayMotors;
  