const Electronics = {
   
    "Cell Phones, Smart Watches & Accessories": {
      "Cell Phone & Smartphone Parts": [],
      "Cell Phone Accessories": [],
      "Cell Phones & Smartphones": [],
      "Display Phones": [],
      "Mixed Lots": [],
      "PDA Accessories": [],
      "PDAs": [],
      "Phone Cards & SIM Cards": [],
      "Smart Watch Accessories": [],
      "Smart Watches": [],
      "Vintage Cell Phones": [],
    },
    "Computers, Tablets & Network Hardware": {
      "3D Printers & Supplies": [],
      "Computer Cables & Connectors": [],
      "Computer Components & Parts": [],
      "Desktops & All-In-Ones": [],
      "Drives, Storage & Blank Media": [],
      "Enterprise Networking, Servers": [],
      "Home Networking & Connectivity": [],
      "Keyboards, Mice & Pointers": [],
      "Laptop & Desktop Accessories": [],
      "Laptops & Netbooks": [],
      "Manuals & Resources": [],
      "Mixed Lots": [],
      "Monitors, Projectors & Accessories": [],
      "Other Computers & Networking": [],
      "Power Protection, Distribution": [],
      "Printers, Scanners & Supplies": [],
      "Software": [],
      "Tablet & eBook Reader Accessories": [],
      "Tablet & eBook Reader Parts": [],
      "Tablets & eBook Readers": [],
    },
    "TV, Video & Home Audio Electronics": {
      "DVD & Blu-ray Players": [],
      "Home Theater Systems": [],
      "Projectors & Screens": [],
      "Receivers & Amplifiers": [],
      "Satellite TV Receivers": [],
      "Streaming Media Players": [],
      "TVs": [],
      "Video Cables & Connectors": [],
      "Other TV, Video & Home Audio": [],
    },
    "Portable Audio & Headphones": {
      "Audio Docks & Mini Speakers": [],
      "Headphones": [],
      "MP3 Players": [],
      "Portable AM/FM Radios": [],
      "Other Portable Audio": [],
    },
    "Major Appliances, Parts & Accessories": {
      "Refrigerators": [],
      "Washing Machines": [],
      "Dryers": [],
      "Microwaves": [],
      "Dishwashers": [],
      "Range Hoods": [],
      "Ovens & Stoves": [],
      "Other Major Appliances": [],
    },
  };
  
  export default Electronics;
  