const HealthAndBeauty = {
  "Bath & Body": {
    "Body Washes & Shower Gels": [],
    "Bath Bombs": [],
    "Body Scrubs": [],
    "Bath Oils": [],
    "Bath Brushes & Sponges": [],
    "Other Bath & Body Products": [],
  },
  "Skin Care": {
    "Moisturizers": [
      "Face Moisturizers",
      "Body Lotions & Moisturizers",
      "Hand & Foot Care",
    ],
    "Cleansers & Toners": [
      "Facial Cleansers",
      "Toners",
      "Makeup Removers",
    ],
    "Treatments & Masks": [
      "Facial Masks",
      "Eye Treatments & Masks",
      "Lip Treatments & Balms",
      "Acne & Blemish Treatments",
    ],
    "Sun Protection": [
      "Sunscreen Products",
      "After Sun Skin Care",
      "Self-Tanners",
    ],
    "Anti-Aging Products": [
      "Serums & Concentrates",
      "Creams & Moisturizers",
      "Eye Treatments",
    ],
    "Other Skin Care Products": [],
  },
  "Hair Care & Styling": {
    "Shampoos & Conditioners": [
      "Shampoos",
      "Conditioners",
      "2-in-1 Shampoo & Conditioner",
    ],
    "Styling Products": [
      "Hair Sprays",
      "Gels & Pomades",
      "Mousses & Foams",
      "Creams & Lotions",
      "Hair Oils & Serums",
    ],
    "Hair Color Products": [
      "Permanent Hair Color",
      "Semi-Permanent Color",
      "Root Touch-Ups",
      "Bleach & Lighteners",
    ],
    "Hair Loss Treatments": [
      "Hair Regrowth Solutions",
      "Laser Combs & Devices",
      "Scalp Treatments",
    ],
    "Hair Accessories": [
      "Hair Brushes & Combs",
      "Hair Clips & Pins",
      "Hair Ties & Elastics",
      "Headbands",
    ],
    "Other Hair Care & Styling": [],
  },
  "Makeup": {
    "Face Makeup": [
      "Foundations",
      "Concealers & Correctors",
      "Powders",
      "Blushes",
      "Bronzers & Highlighters",
      "Primers",
      "BB & CC Creams",
    ],
    "Eye Makeup": [
      "Eyeshadows",
      "Mascaras",
      "Eyeliners",
      "Eyebrow Products",
      "False Eyelashes & Adhesives",
      "Eye Primers",
    ],
    "Lip Makeup": [
      "Lipsticks",
      "Lip Glosses",
      "Lip Liners",
      "Lip Stains",
      "Lip Plumpers",
    ],
    "Makeup Tools & Accessories": [
      "Brushes & Applicators",
      "Sponges & Blenders",
      "Makeup Bags & Cases",
      "Eyelash Curlers",
      "Sharpeners",
    ],
    "Nail Care": [
      "Nail Polish",
      "Gel Nail Polish",
      "Nail Treatments & Strengtheners",
      "Manicure & Pedicure Tools",
      "Artificial Nails & Tips",
    ],
    "Other Makeup Products": [],
  },
  "Fragrances": {
    "Women's Fragrances": [
      "Eau de Parfum",
      "Eau de Toilette",
      "Body Sprays & Mists",
    ],
    "Men's Fragrances": [
      "Cologne",
      "Aftershave",
      "Body Sprays",
    ],
    "Unisex Fragrances": [],
    "Aromatherapy": [
      "Essential Oils",
      "Diffusers",
      "Scented Candles",
    ],
    "Perfume Gift Sets": [],
    "Other Fragrances": [],
  },
  "Health Care": {
    "Vitamins & Dietary Supplements": [
      "Multivitamins",
      "Herbal Supplements",
      "Protein Supplements",
      "Weight Management",
    ],
    "Over-the-Counter Medications": [
      "Pain & Fever Relief",
      "Cough, Cold & Flu",
      "Allergy Medicine",
      "Digestive Aids",
      "Sleep Aids",
    ],
    "First Aid": [
      "Bandages & Dressings",
      "Antiseptics & Ointments",
      "First Aid Kits",
      "Medical Tape",
    ],
    "Health Monitors": [
      "Blood Pressure Monitors",
      "Glucose Monitors",
      "Thermometers",
      "Pulse Oximeters",
    ],
    "Smoking Cessation Products": [
      "Nicotine Gum",
      "Patches",
      "Lozenges",
    ],
    "Other Health Care Products": [],
  },
  "Oral Care": {
    "Toothbrushes": [
      "Manual Toothbrushes",
      "Electric Toothbrushes",
      "Replacement Brush Heads",
    ],
    "Toothpaste": [],
    "Mouthwash & Rinses": [],
    "Dental Floss & Picks": [],
    "Teeth Whitening": [
      "Whitening Kits",
      "Whitening Strips",
      "Whitening Toothpaste",
    ],
    "Other Oral Care Products": [],
  },
  "Shaving & Hair Removal": {
    "Razors & Blades": [
      "Men's Razors",
      "Women's Razors",
      "Disposable Razors",
      "Razor Blades",
    ],
    "Electric Shavers": [
      "Men's Electric Shavers",
      "Women's Electric Shavers",
      "Trimmers & Clippers",
    ],
    "Hair Removal Products": [
      "Depilatory Creams",
      "Waxing Kits",
      "Epilators",
      "Laser Hair Removal Devices",
    ],
    "Shaving Creams & Gels": [],
    "Aftershaves & Pre-Shave": [],
    "Other Shaving & Hair Removal": [],
  },
  "Vision Care": {
    "Reading Glasses": [],
    "Eyeglass Frames": [],
    "Contact Lenses": [],
    "Contact Lens Solutions": [],
    "Eye Drops & Washes": [],
    "Other Vision Care Products": [],
  },
  "Massage": {
    "Massage Oils & Lotions": [],
    "Massage Tools & Equipment": [
      "Handheld Massagers",
      "Massage Chairs",
      "Massage Cushions",
      "Foot Massagers",
    ],
    "Aromatherapy Massage": [],
    "Other Massage Products": [],
  },
  "Sexual Wellness": {
    "Condoms": [],
    "Lubricants": [],
    "Adult Toys & Products": [],
    "Fertility & Ovulation": [],
    "Other Sexual Wellness Products": [],
  },
  "Personal Care Appliances": {
    "Hair Styling Devices": [
      "Hair Dryers",
      "Flat Irons & Hair Straighteners",
      "Curling Irons & Wands",
      "Hot Air Brushes",
    ],
    "Electric Toothbrushes": [],
    "Electric Shavers & Trimmers": [],
    "Massage Devices": [],
    "Other Personal Care Appliances": [],
  },
  "Other Health & Beauty": [],
};

export default HealthAndBeauty;
