'use strict';
const test=require('node:test'); const assert=require('node:assert/strict');
const {isLegacy,reviewState,checkState,summarize}=require('../../../api/engineering-health-model.cjs');
const old={number:53,base:{ref:'feat/older'},user:{login:'author'},created_at:'2026-09-20T00:00:00Z',updated_at:'2026-09-24T00:00:00Z'};
test('protects old customer PRs independently of main or draft state',()=>{assert.equal(isLegacy('GMIsaacson/sourcemargin1.0',old),true); assert.equal(isLegacy('GMIsaacson/sourcemargin1.0',{...old,number:55}),false)});
test('protects stacked Factory branches, not current main PRs',()=>{assert.equal(isLegacy('GMIsaacson/ebaydriva721',old),true);assert.equal(isLegacy('GMIsaacson/ebaydriva721',{...old,base:{ref:'master'}}),false)});
test('unknown and missing CI never become passing',()=>{assert.equal(checkState(null),'UNVERIFIED'); assert.equal(checkState([]),'UNVERIFIED'); assert.equal(checkState([{status:'completed',conclusion:'failure'}]),'FAILED')});
test('review must be supported by actual review records',()=>{assert.equal(reviewState(null,old),'UNVERIFIED');assert.equal(reviewState([],{...old,requested_reviewers:[]}), 'UNREVIEWED');assert.equal(reviewState([{user:{login:'reviewer'},state:'APPROVED'}],old),'APPROVED')});
test('PRs are excluded from issue totals, legacy is separate, age alerts active only',()=>{const r=summarize({name:'GMIsaacson/sourcemargin1.0',label:'Customer',main:'main'},[{...old,html_url:'https://github.com/x/pull/53',title:'old'}, {...old,number:55,html_url:'https://github.com/x/pull/55',title:'new',base:{ref:'main'}}],[{number:54,title:'work',labels:[{name:'regression'}],html_url:'https://github.com/x/issues/54'},{number:55,pull_request:{url:'x'}}],Date.parse('2026-09-26T00:00:00Z'));assert.equal(r.totals.legacyPRs,1);assert.equal(r.totals.activePRs,1);assert.equal(r.totals.openIssues,1);assert.equal(r.totals.taggedRegressions,1);assert.equal(r.totals.aging5d,1);assert.equal(r.totals.checkUnknownActive,1)});
