// src/categoryData.jsx

export const categoryTree = {
  "All Categories": {},
  "eBay Motors": {
    Vehicles: null,
    "Car & Truck Parts": null,
    "Wheels & Tires": null,
    "Motorcycle & Scooter Parts": null,
    "ATV, Side-by-Side & UTV Parts": null,
    "Other Parts & Accessories": null,
    "Automotive Tools & Supplies": null,
    "Automotive Cleaning & Detailing": null,
    "Automotive Paints & Supplies": null,
    "Oils, Fluids, Lubricants & Sealers": null,
    "Safety & Security Accessories": null,
  },
  "Clothing, Shoes & Accessories": {
    Baby: null,
    Kids: null,
    Men: null,
    Specialty: null,
    Women: null,
  },
  "Sporting Goods": {
    "Golf Clubs": null,
    "Electric Bikes": null,
    "Camping & Hiking Equipment": null,
    "Hunting Equipment": null,
    Scooters: null,
    "Shop All Categories": null,
    "Boxing, Martial Arts & MMA": null,
    "Camping & Hiking": null,
    Cycling: null,
    Fishing: null,
    "Fitness, Running & Yoga": null,
    Golf: null,
    Hunting: null,
    "Indoor Games": null,
    "Other Sporting Goods": null,
    "Outdoor Sports": null,
    "Tactical & Duty Gear": null,
    "Team Sports": null,
    "Tennis & Racquet Sports": null,
    "Water Sports": null,
    "Wholesale Lots": null,
    "Winter Sports": null,
  },
  "Toys & Hobbies": {
    "Action Figures & Accessories": null,
    "Beanbag Plush": null,
    "Building Toys": null,
    "Classic Toys": null,
    "Collectible Card Games": null,
    "Diecast & Toy Vehicles": null,
    Educational: null,
    "Electronic, Battery & Wind-Up": null,
    "Fast Food & Cereal Premiums": null,
    Games: null,
    Marbles: null,
    "Model Railroads & Trains": null,
    "Models & Kits": null,
    "Outdoor Toys & Structures": null,
    "Preschool Toys & Pretend Play": null,
    Puzzles: null,
    "Radio Control & Control Line": null,
    "Robots, Monsters & Space Toys": null,
    "Slot Cars": null,
    "Stuffed Animals": null,
    "Toy Soldiers": null,
    "Vintage & Antique Toys": null,
  },
 
  "Jewelry & Watches": {
    "Body Jewelry": null,
    "Children's Jewelry": null,
    "Engagement & Wedding": null,
    "Ethnic, Regional & Tribal": null,
    "Fashion Jewelry": null,
    "Fine Jewelry": null,
    "Handcrafted & Artisan Jewelry": null,
    "Jewelry Care, Design & Repair": null,
    "Jewelry Mixed Lots": null,
    "Loose Beads": null,
    "Loose Diamonds & Gemstones": null,
    "Men's Jewelry": null,
    "Other Jewelry": null,
    "Vintage & Antique Jewelry": null,
    "Watches, Parts & Accessories": null,
  },
  "Health & Beauty": {
    "Bath & Body": null,
    "Electronic Smoking, Parts & Accs": null,
    Fragrances: null,
    "Hair Care & Styling": null,
    "Health Care": null,
    Makeup: null,
    Massage: null,
    "Medical & Mobility": null,
    "Nail Care, Manicure & Pedicure": null,
    "Natural & Alternative Remedies": null,
    "Oral Care": null,
    "Other Health & Beauty": null,
    "Salon & Spa Equipment": null,
    "Shaving & Hair Removal": null,
    "Skin Care": null,
    "Sun Protection & Tanning": null,
    "Tattoos & Body Art": null,
    "Vision Care": null,
    "Vitamins & Lifestyle Supplements": null,
  },

  "Business & Industrial": {},
  "Pet Supplies": {
    "Backyard Poultry Supplies": null,
    "Bird Supplies": null,
    Cameras: null,
    "Cat Supplies": null,
    "Dog Supplies": null,
    "Fish & Aquariums": null,
    "Other Pet Supplies": null,
    "Pet Memorials & Urns": null,
    "Reptile Supplies": null,
    "Small Animal Supplies": null,
    Trackers: null,
  },
  "Baby Essentials": {
    "Baby Gear": null,
    "Baby Safety & Health": null,
    "Bathing & Grooming": null,
    "Car Safety Seats": null,
    "Carriers, Slings & Backpacks": null,
    Diapering: null,
    Feeding: null,
    "Keepsakes & Baby Announcements": null,
    "Nursery Bedding": null,
    "Nursery Décor": null,
    "Nursery Furniture": null,
    "Other Baby": null,
    "Potty Training": null,
    "Strollers & Accessories": null,
  },
  Electronics: {
    "Cameras & Photo": null,
    "Vehicle Electronics & GPS": null,
    "Home Surveillance Systems": null,
    "Surveillance & Smart Home Electronics": null,
    "Major Appliances, Parts & Accessories": null,
    "Video Games & Consoles": null,
    "Virtual Reality Headsets, Parts & Accessories": null,
    "Cell Phones, Smart Watches & Accessories": null,
    "Computers, Tablets & Network Hardware": null,
    "TV, Video & Home Audio Electronics": null,
    "Portable Audio & Headphones": null,
  },
};
